# Generated by Django 5.1.6 on 2025-09-09 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('monthly_harvest_summary', 'Monthly Harvest Summary'), ('yield_performance_report', 'Yield Performance Report'), ('inventory_status_report', 'Inventory Status Report'), ('farm_productivity_analysis', 'Farm Productivity Analysis'), ('crop_performance_report', 'Crop Performance Report'), ('financial_summary_report', 'Financial Summary Report')], max_length=50)),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('seasonal', 'Seasonal'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('last_generated', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('export_format', models.CharField(choices=[('pdf', 'PDF Document'), ('excel', 'Excel Spreadsheet'), ('csv', 'CSV File')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.reporttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ReportActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generate', 'Generate'), ('download', 'Download'), ('view', 'View')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.generatedreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
