# Generated by Django 5.1.6 on 2025-08-13 21:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('total_area_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manager', models.ForeignKey(limit_choices_to={'userprofile_role_in': ['admin', 'farm_manager']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=8)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.farm')),
                ('supervisor', models.ForeignKey(limit_choices_to={'userprofile_role_in': ['field_supervisor', 'farm_manager']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity_tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Good'), ('C', 'Grade C - Average'), ('D', 'Grade D - Below Average')], max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.field')),
                ('harvested_by', models.ForeignKey(limit_choices_to={'userprofile_role_in': ['field_worker', 'field_supervisor']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage_location', models.CharField(max_length=200)),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Good'), ('C', 'Grade C - Average'), ('D', 'Grade D - Below Average')], max_length=1)),
                ('date_stored', models.DateField(default=django.utils.timezone.now)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.crop')),
                ('managed_by', models.ForeignKey(limit_choices_to={'userprofile__role__in': ['inventory_manager', 'admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
