# Generated by Django 5.1.6 on 2025-09-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farm_manager', 'Farm Manager'), ('field_supervisor', 'Field Supervisor'), ('field_worker', 'Field Worker'), ('inventory_manager', 'Inventory Manager')], default='field_worker', max_length=20),
        ),
    ]
