# Generated by Django 5.1.6 on 2025-09-11 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_inventory_models'),
        ('monitoring', '0002_reporttemplate_generatedreport_reportactivitylog'),
    ]

    operations = [
    ]
