# Generated by Django 5.2 on 2025-09-12 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_merge_20250911_0107'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='monitoring__crop_ty_c70266_idx',
            old_name='monitoring_i_crop_ty_b6b89a_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='monitoring__expiry__9bc6a6_idx',
            old_name='monitoring_i_expiry__cc8f44_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryitem',
            new_name='monitoring__date_st_610caa_idx',
            old_name='monitoring_i_date_st_a4d67f_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorytransaction',
            new_name='monitoring__timesta_1acb25_idx',
            old_name='monitoring_i_timesta_a8b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorytransaction',
            new_name='monitoring__action__3c3af8_idx',
            old_name='monitoring_i_action__d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorytransaction',
            new_name='monitoring__user_id_c715db_idx',
            old_name='monitoring_i_user_id_g7h8i9_idx',
        ),
        migrations.AddField(
            model_name='farm',
            name='calculated_avg_yield',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AddField(
            model_name='farm',
            name='calculated_field_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='farm',
            name='calculated_total_area',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='farm',
            name='crop_types',
            field=models.ManyToManyField(blank=True, related_name='farms', to='monitoring.croptype'),
        ),
        migrations.AddField(
            model_name='field',
            name='soil_quality',
            field=models.CharField(blank=True, choices=[('', 'Select quality'), ('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='croptype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='field',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_set', to='monitoring.farm'),
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvestrecord_set', to='monitoring.field'),
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='quality_grade',
            field=models.CharField(choices=[('A', 'Grade A - Premium'), ('B', 'Grade B - Good'), ('C', 'Grade C - Average'), ('D', 'Grade D - Below Average')], max_length=1),
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
